export type TabKey = 'chat' | 'feed' | 'scan' | 'payment' | 'identity';

export type ScreenKey =
  | 'wallet'
  | 'news-feed'
  | 'news-feed-search'
  | 'compose-post'
  | 'live-stream'
  | 'payment'
  | 'credentials'
  | 'profile'
  | 'security'
  | 'share'
  | 'share-qr'
  | 'connection-qr'
  | 'chat-list'
  | 'chat'
  | 'notifications'
  | 'scan'
  | 'activity'
  | 'settings'
  | 'settings-backup'
  | 'settings-display'
  | 'settings-governance'
  | 'settings-notifications'
  | 'settings-sharing'
  | 'settings-data'
  | 'settings-help'
  | 'settings-about';
