import { MAIN_TOP_HEADER_ROW_HEIGHT } from '../../../components/MainTopHeader';

export const NEWS_FEED_HEADER_HEIGHT = MAIN_TOP_HEADER_ROW_HEIGHT;
export const NEWS_FEED_TABS_HEIGHT = 62;
export const NEWS_FEED_OVERLAY_HEIGHT = NEWS_FEED_HEADER_HEIGHT + NEWS_FEED_TABS_HEIGHT;
