import { StyleSheet } from 'react-native';
import { border, palette, radius, shadows, spacing, touchTarget, typography } from '../../../theme';
import { NEWS_FEED_HEADER_HEIGHT, NEWS_FEED_OVERLAY_HEIGHT, NEWS_FEED_TABS_HEIGHT } from './newsFeedLayout';

export const newsFeedStyles = StyleSheet.create({
  screen: { flex: 1 },
  headerOverlay: { position: 'absolute', top: 0, right: 0, left: 0, zIndex: 4 },
  tabsOverlay: { position: 'absolute', top: NEWS_FEED_HEADER_HEIGHT, right: 0, left: 0, zIndex: 5 },
  header: {
    minHeight: NEWS_FEED_HEADER_HEIGHT,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  iconButton: { width: touchTarget.minimum, height: touchTarget.minimum, borderRadius: radius.round, alignItems: 'center', justifyContent: 'center' },
  brand: { flexShrink: 0 },
  searchBox: {
    flex: 1,
    minWidth: 92,
    minHeight: 46,
    borderRadius: radius.round,
    borderWidth: border.thin,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  searchPlaceholder: { flex: 1, fontSize: typography.size.md, fontWeight: typography.weight.medium },
  notificationBadge: {
    position: 'absolute',
    top: 4,
    right: 2,
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#F02850',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
  },
  notificationBadgeText: { color: palette.white, fontSize: typography.size.sm, fontWeight: typography.weight.black },
  tabs: { minHeight: NEWS_FEED_TABS_HEIGHT, borderBottomWidth: border.thin, flexDirection: 'row', alignItems: 'flex-end' },
  tab: { flex: 1, minHeight: NEWS_FEED_TABS_HEIGHT, alignItems: 'center', justifyContent: 'flex-end', paddingBottom: spacing.md, position: 'relative' },
  activeTabText: { fontSize: typography.size.md, fontWeight: typography.weight.black },
  tabText: { fontSize: typography.size.md, fontWeight: typography.weight.semibold },
  activeIndicator: { position: 'absolute', bottom: 0, width: '72%', height: 3, borderTopLeftRadius: 2, borderTopRightRadius: 2 },
  content: { paddingTop: NEWS_FEED_OVERLAY_HEIGHT, paddingBottom: 108 },
  livePost: { borderBottomWidth: border.thin, paddingHorizontal: spacing.md, paddingVertical: spacing.lg, flexDirection: 'row', gap: spacing.md },
  livePostAvatarWrap: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: border.thick,
    borderColor: palette.blue[700],
    padding: 2,
  },
  livePostAvatar: { width: '100%', height: '100%', borderRadius: radius.round, backgroundColor: palette.gray[100] },
  livePostMetaRow: { minHeight: 24, flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  livePostName: { maxWidth: 100, flexShrink: 1, fontSize: typography.size.md, fontWeight: typography.weight.black },
  livePostHandle: { maxWidth: 82, flexShrink: 1, fontSize: typography.size.sm, fontWeight: typography.weight.medium },
  livePostTime: { flexShrink: 0, fontSize: typography.size.sm, fontWeight: typography.weight.medium },
  livePostMore: { marginLeft: 'auto' },
  liveStateRow: { marginTop: spacing.xs, flexDirection: 'row', alignItems: 'center' },
  liveMetaPill: { borderRadius: radius.round, backgroundColor: 'rgba(53, 92, 255, 0.14)', paddingHorizontal: spacing.sm, paddingVertical: spacing.xxs },
  liveMetaPillText: { color: palette.blue[700], fontSize: typography.size.xs + 1, lineHeight: 17, fontWeight: typography.weight.semibold },
  livePostText: { marginTop: spacing.sm, fontSize: typography.size.md, lineHeight: typography.lineHeight.md, fontWeight: typography.weight.regular },
  livePreviewFrame: {
    marginTop: spacing.md,
    width: '100%',
    aspectRatio: 0.92,
    borderRadius: radius.xl,
    overflow: 'hidden',
    backgroundColor: palette.gray[100],
  },
  livePreviewImage: { flex: 1 },
  livePreviewImageRadius: { borderRadius: radius.xl },
  livePreviewOverlay: { flex: 1, padding: spacing.sm, justifyContent: 'space-between' },
  livePreviewTop: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  liveBadge: {
    minHeight: 26,
    borderRadius: radius.sm,
    backgroundColor: '#E62C5B',
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  liveBadgeDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: palette.white },
  liveBadgeText: { color: palette.white, fontSize: 10, fontWeight: typography.weight.black, letterSpacing: 0.2 },
  liveViewerCount: {
    minHeight: 26,
    borderRadius: radius.sm,
    backgroundColor: 'rgba(15, 23, 42, 0.58)',
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  liveViewerCountText: { color: palette.white, fontSize: typography.size.xs, fontWeight: typography.weight.semibold },
  livePreviewBody: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: spacing.sm },
  liveCommentStack: { flex: 1, gap: spacing.xs },
  liveCommentBubble: {
    maxWidth: 166,
    minHeight: 40,
    borderRadius: radius.lg,
    backgroundColor: 'rgba(11, 15, 26, 0.46)',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  liveCommentAvatar: { width: 28, height: 28, borderRadius: 14, backgroundColor: palette.gray[100] },
  liveCommentCopy: { flex: 1, minWidth: 0 },
  liveCommentName: { color: palette.white, fontSize: typography.size.xs, fontWeight: typography.weight.black },
  liveCommentText: { marginTop: spacing.xxs, color: palette.white, fontSize: typography.size.xs, fontWeight: typography.weight.medium },
  liveReactionRail: { width: 32, alignItems: 'center', gap: spacing.xs },
  liveReactionAvatarWrap: { width: 30, height: 30, borderRadius: 15 },
  liveReactionAvatar: { width: 30, height: 30, borderRadius: 15, backgroundColor: palette.gray[100] },
  liveReactionIcon: {
    position: 'absolute',
    right: -5,
    bottom: -3,
    width: 17,
    height: 17,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveReactionMore: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(11, 15, 26, 0.64)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveReactionMoreText: { color: palette.white, fontSize: typography.size.xs, fontWeight: typography.weight.semibold },
  liveComposerRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  liveComposerIconButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(15, 23, 42, 0.62)',
    borderWidth: border.hairline,
    borderColor: 'rgba(255,255,255,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveComposerInput: {
    flex: 1,
    minWidth: 0,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    borderWidth: border.hairline,
    borderColor: 'rgba(255,255,255,0.22)',
    paddingLeft: spacing.md,
    paddingRight: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  liveComposerPlaceholder: { flex: 1, color: 'rgba(255,255,255,0.82)', fontSize: typography.size.xs, fontWeight: typography.weight.medium },
  liveHeartButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F02850',
    alignItems: 'center',
    justifyContent: 'center',
  },
  post: { borderBottomWidth: border.thin, paddingHorizontal: spacing.md, paddingVertical: spacing.lg, flexDirection: 'row', gap: spacing.md },
  avatarColumn: { width: 52, alignItems: 'center' },
  identraAvatar: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center' },
  identraAvatarInner: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' },
  genfestAvatar: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center' },
  genfestAvatarText: { color: palette.white, fontSize: 11, fontWeight: typography.weight.black, letterSpacing: -0.3 },
  initialAvatar: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center' },
  initialAvatarText: { color: palette.white, fontSize: typography.size.md, fontWeight: typography.weight.black },
  postBody: { flex: 1, minWidth: 0 },
  postMetaRow: { minHeight: 24, flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  authorName: { maxWidth: 112, fontSize: typography.size.md, fontWeight: typography.weight.black },
  authorMeta: { flex: 1, fontSize: typography.size.sm, fontWeight: typography.weight.medium },
  moreIcon: { marginLeft: 'auto' },
  postText: { marginTop: spacing.xs, fontSize: typography.size.md, lineHeight: 23, fontWeight: typography.weight.regular },
  verifiedBadge: { width: 17, height: 17, flexShrink: 0 },
  imageWrap: {
    marginTop: spacing.md,
    width: '94%',
    maxWidth: 318,
    aspectRatio: 1.88,
    alignSelf: 'flex-start',
    borderRadius: radius.xl,
    overflow: 'hidden',
    backgroundColor: palette.gray[100],
  },
  postImage: { width: '100%', height: '100%' },
  imageBadge: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.sm,
    minWidth: 45,
    height: 32,
    borderRadius: radius.round,
    backgroundColor: 'rgba(15, 23, 42, 0.62)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
  },
  imageBadgeText: { color: palette.white, fontSize: typography.size.sm, fontWeight: typography.weight.semibold },
  smartContractCard: {
    marginTop: spacing.md,
    width: '100%',
    borderWidth: border.thin,
    borderRadius: radius.xl,
    padding: spacing.md,
    gap: spacing.md,
    ...shadows.subtle,
  },
  smartContractHeader: { alignItems: 'flex-start', gap: spacing.sm },
  smartContractTitle: { fontSize: typography.size.md, lineHeight: typography.lineHeight.md, fontWeight: typography.weight.black },
  smartStatusPill: {
    minHeight: 30,
    borderRadius: radius.round,
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  smartStatusText: { flexShrink: 1, fontSize: typography.size.xs, fontWeight: typography.weight.extraBold },
  smartTradeRow: { gap: spacing.sm },
  smartTradePanel: {
    borderWidth: border.thin,
    borderRadius: radius.md,
    padding: spacing.sm,
    gap: spacing.sm,
  },
  smartPaymentPanel: { backgroundColor: '#F1FCF5' },
  smartTradeLabel: { fontSize: typography.size.xs, lineHeight: typography.lineHeight.xs, fontWeight: typography.weight.semibold },
  smartTicketRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  smartTicketArt: {
    width: 46,
    height: 40,
    borderRadius: radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1,
  },
  smartTicketBrand: { color: palette.white, fontSize: 6.8, lineHeight: 8, fontWeight: typography.weight.black, letterSpacing: 0.2 },
  smartTicketYear: { color: 'rgba(255,255,255,0.8)', fontSize: 6.5, lineHeight: 8, fontWeight: typography.weight.semibold },
  smartTicketCopy: { flex: 1, minWidth: 0, gap: 2 },
  smartTicketTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  smartTicketTitle: { flex: 1, minWidth: 0, fontSize: 10.5, lineHeight: 14, fontWeight: typography.weight.extraBold },
  smartTinyBadge: { width: 11, height: 11, flexShrink: 0 },
  smartTicketMeta: { fontSize: 8.5, lineHeight: 12, fontWeight: typography.weight.medium },
  smartSoldOutMetaRow: { marginTop: spacing.xs, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  smartAssetStatePill: { borderRadius: radius.round, paddingHorizontal: spacing.sm, paddingVertical: 3 },
  smartAssetStateText: { fontSize: 10, lineHeight: 12, fontWeight: typography.weight.extraBold },
  smartRemainingText: { flex: 1, minWidth: 0, fontSize: 10, lineHeight: 13, fontWeight: typography.weight.semibold },
  smartPaymentBox: {
    minHeight: 58,
    borderRadius: radius.md,
    backgroundColor: palette.green[100],
    paddingHorizontal: spacing.sm,
    justifyContent: 'center',
    gap: 3,
  },
  smartAmount: { color: '#159447', fontSize: typography.size.md, lineHeight: typography.lineHeight.sm, fontWeight: typography.weight.black },
  smartPaymentText: { color: '#159447', fontSize: 10.5, lineHeight: 14, fontWeight: typography.weight.semibold },
  smartLimitNotice: {
    minHeight: 34,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  smartLimitNoticeText: { flex: 1, minWidth: 0, fontSize: 10.5, lineHeight: 15, fontWeight: typography.weight.semibold },
  smartInfoList: { borderWidth: border.thin, borderRadius: radius.md, overflow: 'hidden' },
  smartInfoRow: { minHeight: 36, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  smartInfoLabelWrap: { width: 116, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  smartInfoLabel: { flex: 1, minWidth: 0, fontSize: 10.5, lineHeight: 14, fontWeight: typography.weight.semibold },
  smartInfoValue: { flex: 1, minWidth: 0, textAlign: 'right', fontSize: 10.5, lineHeight: 15, fontWeight: typography.weight.semibold },
  smartContractActions: { flexDirection: 'row', gap: spacing.sm },
  smartRejectButton: {
    flex: 1,
    minHeight: 44,
    borderWidth: border.thin,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smartPrimaryButton: { flex: 1, minHeight: 44, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' },
  smartRejectText: { fontSize: typography.size.sm, fontWeight: typography.weight.black },
  smartPrimaryText: { color: palette.white, fontSize: typography.size.sm, fontWeight: typography.weight.black },
  actions: { marginTop: spacing.md, minHeight: 30, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  action: { minHeight: touchTarget.minimum, minWidth: touchTarget.minimum, flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  actionText: { fontSize: typography.size.sm, fontWeight: typography.weight.medium },
  fab: {
    position: 'absolute',
    right: spacing.xl,
    bottom: 92,
    zIndex: 5,
  },
  fabButton: {
    width: 66,
    height: 66,
    borderRadius: 33,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.floating,
  },
});
