import { StyleSheet } from 'react-native';

import { border, layout, palette, radius, spacing, touchTarget, typography } from '../../../theme';

export const paymentHomeStyles = StyleSheet.create({
  screenContent: {
    paddingTop: spacing.sm,
    paddingBottom: spacing.xxl,
    gap: spacing.lg,
  },
  header: {
    minHeight: layout.appBarHeight,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  headerIconButton: {
    width: touchTarget.minimum,
    height: touchTarget.minimum,
    borderRadius: radius.round,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandName: {
    flex: 1,
    fontSize: typography.size.xl,
    lineHeight: typography.lineHeight.xl,
    fontWeight: typography.weight.black,
    letterSpacing: 0,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  circleActionButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: border.hairline,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    minWidth: 23,
    height: 23,
    borderRadius: 12,
    backgroundColor: palette.red[500],
    borderWidth: border.thick,
    borderColor: palette.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
  },
  notificationBadgeText: {
    color: palette.white,
    fontSize: 11,
    fontWeight: typography.weight.black,
  },
  heroScroller: {
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
  },
  heroShadowFrame: {
    borderRadius: radius.xxl,
    backgroundColor: palette.blue[700],
  },
  heroCard: {
    flex: 1,
    borderRadius: radius.xxl,
    overflow: 'hidden',
    padding: spacing.xl,
    justifyContent: 'space-between',
  },
  cardAuraLarge: {
    position: 'absolute',
    right: -52,
    top: 74,
    width: 194,
    height: 194,
    borderRadius: 97,
    borderWidth: 44,
    borderColor: 'rgba(255,255,255,0.14)',
    transform: [{ rotate: '-20deg' }],
  },
  cardAuraSmall: {
    position: 'absolute',
    right: 36,
    top: 66,
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: 'rgba(255,255,255,0.22)',
    transform: [{ rotate: '-20deg' }],
  },
  cardSweep: {
    position: 'absolute',
    left: -40,
    right: -20,
    top: 48,
    height: 120,
    borderRadius: 60,
    borderWidth: border.hairline,
    borderColor: 'rgba(255,255,255,0.08)',
    transform: [{ rotate: '-7deg' }],
  },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  manageButton: {
    minHeight: 44,
    borderRadius: radius.lg,
    backgroundColor: 'rgba(255,255,255,0.13)',
    borderWidth: border.hairline,
    borderColor: 'rgba(255,255,255,0.16)',
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  manageButtonText: {
    color: palette.white,
    fontSize: typography.size.sm,
    fontWeight: typography.weight.extraBold,
  },
  cardBrand: {
    color: palette.white,
    fontSize: 30,
    lineHeight: 34,
    fontWeight: typography.weight.black,
    fontStyle: 'italic',
    letterSpacing: 0,
  },
  cardBrandStack: {
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  cardDetailButton: {
    minHeight: 26,
    borderRadius: radius.round,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: border.hairline,
    borderColor: 'rgba(255,255,255,0.2)',
    paddingLeft: spacing.sm,
    paddingRight: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
  },
  cardDetailText: {
    color: palette.white,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: typography.weight.black,
  },
  cardMiddle: {
    gap: spacing.sm,
  },
  chipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
  },
  chip: {
    width: 43,
    height: 33,
    borderRadius: radius.sm,
    backgroundColor: '#F8D681',
    borderWidth: border.hairline,
    borderColor: 'rgba(255,255,255,0.52)',
    overflow: 'hidden',
  },
  chipLineHorizontal: {
    position: 'absolute',
    top: 15,
    right: 0,
    left: 0,
    height: border.hairline,
    backgroundColor: 'rgba(90,61,17,0.45)',
  },
  chipLineVertical: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 18,
    width: border.hairline,
    backgroundColor: 'rgba(90,61,17,0.45)',
  },
  contactlessIcon: {
    transform: [{ rotate: '90deg' }],
  },
  cardNumberRow: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  cardNumber: {
    flex: 1,
    color: palette.white,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: typography.weight.black,
    letterSpacing: 0,
    fontVariant: ['tabular-nums'],
  },
  cardMetaRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.xl,
  },
  expiryBlock: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.sm,
  },
  holderBlock: {
    flex: 1,
    minWidth: 0,
  },
  cardMetaLabel: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: typography.weight.medium,
  },
  expiryText: {
    color: palette.white,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: typography.weight.black,
    fontVariant: ['tabular-nums'],
  },
  holderText: {
    marginTop: spacing.xs,
    color: palette.white,
    fontSize: typography.size.sm,
    lineHeight: typography.lineHeight.sm,
    fontWeight: typography.weight.black,
    letterSpacing: 0,
  },
  cardBottomRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  balanceBlock: {
    flex: 1,
    minWidth: 0,
  },
  balanceLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  balanceLabel: {
    flexShrink: 1,
    color: 'rgba(255,255,255,0.88)',
    fontSize: typography.size.sm,
    lineHeight: typography.lineHeight.sm,
    fontWeight: typography.weight.semibold,
    textTransform: 'uppercase',
  },
  balanceValueRow: {
    marginTop: spacing.xs,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  balanceValue: {
    maxWidth: '78%',
    color: palette.white,
    fontSize: 30,
    lineHeight: 35,
    fontWeight: typography.weight.black,
    letterSpacing: 0,
    fontVariant: ['tabular-nums'],
  },
  balanceCurrency: {
    color: palette.white,
    fontSize: typography.size.lg,
    lineHeight: 27,
    fontWeight: typography.weight.black,
  },
  cvvButton: {
    minWidth: 126,
    minHeight: 46,
    borderRadius: radius.lg,
    backgroundColor: 'rgba(255,255,255,0.13)',
    borderWidth: border.hairline,
    borderColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  cvvButtonText: {
    color: palette.white,
    fontSize: typography.size.sm,
    fontWeight: typography.weight.black,
  },
  pagination: {
    minHeight: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  paginationCompact: {
    minHeight: 14,
    marginTop: -spacing.xs,
  },
  paginationDot: {
    height: 6,
    borderRadius: radius.round,
  },
  paginationDotCompact: {
    height: 6,
  },
  sectionHeader: {
    minHeight: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xxs,
  },
  sectionTitle: {
    fontSize: typography.size.lg,
    lineHeight: typography.lineHeight.lg,
    fontWeight: typography.weight.black,
    letterSpacing: 0,
  },
  sectionAction: {
    fontSize: typography.size.md,
    fontWeight: typography.weight.extraBold,
  },
  quickScroller: {
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
  },
  quickGrid: {
    height: 222,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  actionCard: {
    height: 104,
    borderRadius: radius.lg,
    borderWidth: border.hairline,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.md,
    gap: spacing.sm,
  },
  actionSoonBadge: {
    position: 'absolute',
    top: spacing.xs,
    right: spacing.xs,
    minHeight: 20,
    borderRadius: radius.round,
    borderWidth: border.hairline,
    paddingHorizontal: spacing.xs,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionSoonText: {
    fontSize: 9,
    fontWeight: typography.weight.black,
  },
  actionCardCompact: {
    height: 112,
  },
  actionIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionIconWrapCompact: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  actionLabel: {
    minHeight: 36,
    fontSize: typography.size.sm,
    lineHeight: 18,
    fontWeight: typography.weight.extraBold,
    textAlign: 'center',
  },
  actionLabelCompact: {
    minHeight: 38,
    fontSize: typography.size.xs,
    lineHeight: typography.lineHeight.xs,
  },
  bannerScroller: {
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
  },
  promoCard: {
    minHeight: 178,
    marginRight: spacing.md,
    borderRadius: radius.xl,
    borderWidth: border.hairline,
    overflow: 'hidden',
    padding: spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
  },
  promoCopy: {
    width: '54%',
    zIndex: 1,
  },
  promoTitle: {
    color: palette.navy[800],
    fontSize: typography.size.lg,
    lineHeight: typography.lineHeight.lg + 1,
    fontWeight: typography.weight.black,
    letterSpacing: 0,
  },
  promoDescription: {
    marginTop: spacing.sm,
    color: palette.navy[600],
    fontSize: typography.size.sm,
    lineHeight: typography.lineHeight.sm + 1,
    fontWeight: typography.weight.medium,
  },
  promoButton: {
    alignSelf: 'flex-start',
    minHeight: 42,
    marginTop: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: palette.blue[500],
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  promoButtonText: {
    color: palette.white,
    fontSize: typography.size.sm,
    fontWeight: typography.weight.black,
  },
  promoArt: {
    flex: 1,
    minHeight: 138,
    alignItems: 'center',
    justifyContent: 'center',
  },
  promoPhone: {
    width: 82,
    height: 132,
    borderRadius: 20,
    backgroundColor: palette.navy[800],
    padding: 7,
    transform: [{ rotate: '10deg' }],
  },
  promoPhoneSpeaker: {
    alignSelf: 'center',
    width: 28,
    height: 5,
    borderRadius: radius.round,
    backgroundColor: 'rgba(255,255,255,0.2)',
    marginBottom: 7,
  },
  promoPhoneScreen: {
    flex: 1,
    borderRadius: radius.lg,
    backgroundColor: palette.blue[500],
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  promoPhoneText: {
    color: palette.white,
    fontSize: 11,
    fontWeight: typography.weight.black,
    letterSpacing: 0,
  },
  promoCoin: {
    position: 'absolute',
    left: 0,
    top: 24,
    width: 43,
    height: 43,
    borderRadius: 22,
    backgroundColor: '#FFE0A6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  promoShield: {
    position: 'absolute',
    right: 0,
    bottom: 12,
    width: 52,
    height: 52,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.72)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  suggestionScroller: {
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    gap: spacing.md,
  },
  offerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  offerCard: {
    minHeight: 202,
    borderRadius: radius.lg,
    borderWidth: border.hairline,
    overflow: 'hidden',
  },
  offerVisual: {
    height: 112,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerBubbleLarge: {
    position: 'absolute',
    right: -20,
    top: -22,
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  offerBubbleSmall: {
    position: 'absolute',
    left: 18,
    bottom: 18,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.38)',
  },
  offerIconPlate: {
    width: 64,
    height: 64,
    borderRadius: 23,
    backgroundColor: 'rgba(255,255,255,0.78)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerTitle: {
    marginTop: spacing.md,
    paddingHorizontal: spacing.md,
    fontSize: typography.size.sm,
    lineHeight: typography.lineHeight.sm,
    fontWeight: typography.weight.black,
  },
  offerDescription: {
    marginTop: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
    fontSize: typography.size.xs,
    lineHeight: typography.lineHeight.xs,
    fontWeight: typography.weight.medium,
  },
});
