import { StyleSheet } from 'react-native';

import { border, palette, radius, spacing, typography } from '../../../theme';

export const paymentHomeStyles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  screenContent: {
    paddingTop: spacing.sm,
    paddingBottom: spacing.xxl,
    gap: spacing.md + spacing.xs,
  },
  heroScroller: {
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
  },
  heroShadowFrame: {
    borderRadius: radius.xxl,
    backgroundColor: palette.blue[700],
  },
  heroCard: {
    flex: 1,
    borderRadius: radius.xxl,
    overflow: 'hidden',
    padding: spacing.lg + spacing.xs,
    justifyContent: 'space-between',
  },
  cardAuraLarge: {
    position: 'absolute',
    right: -52,
    top: 74,
    width: 194,
    height: 194,
    borderRadius: 97,
    borderWidth: 44,
    borderColor: 'rgba(255,255,255,0.14)',
    transform: [{ rotate: '-20deg' }],
  },
  cardAuraSmall: {
    position: 'absolute',
    right: 36,
    top: 66,
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: 'rgba(255,255,255,0.22)',
    transform: [{ rotate: '-20deg' }],
  },
  cardSweep: {
    position: 'absolute',
    left: -40,
    right: -20,
    top: 48,
    height: 120,
    borderRadius: 60,
    borderWidth: border.hairline,
    borderColor: 'rgba(255,255,255,0.08)',
    transform: [{ rotate: '-7deg' }],
  },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  manageButton: {
    minHeight: 40,
    borderRadius: radius.md + 2,
    backgroundColor: 'rgba(255,255,255,0.13)',
    borderWidth: border.hairline,
    borderColor: 'rgba(255,255,255,0.16)',
    paddingHorizontal: spacing.sm + spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs + 1,
  },
  manageButtonText: {
    color: palette.white,
    fontSize: typography.size.xs + 1,
    lineHeight: 18,
    fontWeight: typography.weight.semibold,
  },
  cardBrand: {
    color: palette.white,
    fontSize: 27,
    lineHeight: 32,
    fontWeight: typography.weight.extraBold,
    fontStyle: 'italic',
    letterSpacing: 0,
  },
  cardBrandStack: {
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  cardDetailButton: {
    minHeight: 26,
    borderRadius: radius.round,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: border.hairline,
    borderColor: 'rgba(255,255,255,0.2)',
    paddingLeft: spacing.sm,
    paddingRight: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
  },
  cardDetailText: {
    color: palette.white,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: typography.weight.semibold,
  },
  cardMiddle: {
    gap: spacing.sm + spacing.xxs,
  },
  chipRow: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
  },
  chip: {
    width: 43,
    height: 33,
    borderRadius: radius.sm,
    backgroundColor: '#F8D681',
    borderWidth: border.hairline,
    borderColor: 'rgba(255,255,255,0.52)',
    overflow: 'hidden',
  },
  chipLineHorizontal: {
    position: 'absolute',
    top: 15,
    right: 0,
    left: 0,
    height: border.hairline,
    backgroundColor: 'rgba(90,61,17,0.45)',
  },
  chipLineVertical: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 18,
    width: border.hairline,
    backgroundColor: 'rgba(90,61,17,0.45)',
  },
  contactlessIcon: {
    transform: [{ rotate: '90deg' }],
  },
  cardNumberRow: {
    minHeight: 36,
    alignSelf: 'flex-start',
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs + 2,
  },
  cardNumber: {
    flexShrink: 1,
    color: palette.white,
    fontSize: 27,
    lineHeight: 34,
    fontWeight: typography.weight.extraBold,
    letterSpacing: 0,
    fontVariant: ['tabular-nums'],
  },
  cardMetaRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: spacing.lg,
  },
  expiryBlock: {
    width: 76,
    gap: spacing.xxs,
  },
  holderBlock: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xxs,
  },
  cardMetaLabel: {
    color: 'rgba(255,255,255,0.76)',
    fontSize: typography.size.xs,
    lineHeight: 14,
    fontWeight: typography.weight.medium,
  },
  expiryText: {
    color: palette.white,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: typography.weight.semibold,
    fontVariant: ['tabular-nums'],
  },
  holderText: {
    color: palette.white,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: typography.weight.semibold,
    letterSpacing: 0,
  },
  cardBottomRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  balanceBlock: {
    flex: 1,
    minWidth: 0,
  },
  balanceLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  balanceLabel: {
    flexShrink: 1,
    color: 'rgba(255,255,255,0.78)',
    fontSize: typography.size.xs,
    lineHeight: 14,
    fontWeight: typography.weight.medium,
  },
  balanceValueRow: {
    marginTop: spacing.xs,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  balanceValue: {
    flexShrink: 1,
    color: palette.white,
    fontSize: 21,
    lineHeight: 29,
    fontWeight: typography.weight.semibold,
    letterSpacing: 0,
    fontVariant: ['tabular-nums'],
  },
  balanceCurrency: {
    flexShrink: 0,
    color: palette.white,
    fontSize: typography.size.md,
    lineHeight: 24,
    fontWeight: typography.weight.semibold,
  },
  cvvButton: {
    flexShrink: 0,
    minWidth: 122,
    minHeight: 42,
    marginTop: 14,
    borderRadius: radius.md + 2,
    backgroundColor: 'rgba(255,255,255,0.13)',
    borderWidth: border.hairline,
    borderColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: spacing.sm + spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs + 1,
  },
  cvvButtonText: {
    flexShrink: 1,
    color: palette.white,
    fontSize: typography.size.xs,
    lineHeight: 17,
    fontWeight: typography.weight.semibold,
  },
  pagination: {
    minHeight: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  paginationCompact: {
    minHeight: 14,
    marginTop: spacing.xs,
  },
  paginationDot: {
    height: 6,
    borderRadius: radius.round,
  },
  paginationDotCompact: {
    height: 6,
  },
  sectionHeader: {
    minHeight: 26,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingHorizontal: spacing.xxs,
  },
  sectionTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: typography.weight.semibold,
    letterSpacing: 0,
  },
  sectionAction: {
    flexShrink: 0,
    fontSize: typography.size.sm,
    lineHeight: typography.lineHeight.sm,
    fontWeight: typography.weight.medium,
  },
  quickPanel: {
    borderWidth: border.hairline,
    borderRadius: radius.xl,
    overflow: 'hidden',
    paddingVertical: spacing.md,
  },
  quickScroller: {
    paddingHorizontal: spacing.sm,
    paddingTop: 0,
    paddingBottom: 0,
  },
  quickGrid: {
    height: 184,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  actionCard: {
    height: 88,
    borderRadius: radius.md,
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xxs,
    paddingVertical: spacing.xs,
    gap: spacing.xs + 1,
  },
  actionSoonBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    minHeight: 21,
    borderRadius: radius.round,
    borderWidth: border.hairline,
    paddingHorizontal: spacing.xs,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionSoonText: {
    fontSize: typography.size.xs,
    lineHeight: 15,
    fontWeight: typography.weight.semibold,
  },
  actionCardCompact: {
    height: 116,
  },
  actionIconWrap: {
    width: 52,
    height: 52,
    borderRadius: radius.lg + 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionIconWrapCompact: {
    width: 52,
    height: 52,
    borderRadius: radius.lg + 2,
  },
  actionLabel: {
    minHeight: 31,
    fontSize: typography.size.xs,
    lineHeight: 15,
    fontWeight: typography.weight.medium,
    textAlign: 'center',
  },
  actionLabelCompact: {
    minHeight: 45,
    fontSize: typography.size.xs,
    lineHeight: 15,
  },
  demoBannerFrame: {
    borderRadius: radius.xl,
    borderWidth: border.hairline,
    overflow: 'hidden',
  },
  demoBannerTrack: {},
  demoBannerSlide: {
    flexShrink: 0,
    overflow: 'hidden',
    backfaceVisibility: 'hidden',
  },
  demoBannerImage: {
    flexShrink: 0,
  },
  demoBannerIndicator: {
    position: 'absolute',
    top: 0,
    right: spacing.sm,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  demoBannerIndicatorDot: {
    width: 6,
    borderRadius: radius.round,
  },
  suggestionScroller: {
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    gap: spacing.sm + spacing.xs,
  },
  offerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  offerCard: {
    minHeight: 178,
    borderRadius: radius.lg,
    borderWidth: border.hairline,
    overflow: 'hidden',
  },
  offerVisual: {
    aspectRatio: 2,
    overflow: 'hidden',
  },
  offerImage: {
    width: '100%',
    height: '100%',
  },
  offerTitle: {
    marginTop: spacing.sm,
    paddingHorizontal: spacing.sm + spacing.xs,
    fontSize: typography.size.xs,
    lineHeight: typography.lineHeight.xs,
    fontWeight: typography.weight.semibold,
  },
  offerDescription: {
    marginTop: spacing.xxs,
    paddingHorizontal: spacing.sm + spacing.xs,
    paddingBottom: spacing.sm + spacing.xs,
    fontSize: typography.size.xs,
    lineHeight: typography.lineHeight.xs,
    fontWeight: typography.weight.medium,
  },
});
