import { StyleSheet } from 'react-native';
import { border, layout, palette, radius, spacing, typography } from '../../theme';
import {
  CHAT_LIST_HEADER_HEIGHT,
  LIST_AVATAR_SIZE,
  QUICK_AVATAR_SIZE,
  QUICK_CONTACT_WIDTH,
  THOUGHT_BUBBLE_HEIGHT,
  THOUGHT_BUBBLE_OVERLAP,
  THOUGHT_BUBBLE_WIDTH,
} from './ChatListData';

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  defaultLayer: { flex: 1 },
  thoughtViewerContainer: { flex: 1, paddingHorizontal: 18 },
  thoughtViewerHeader: { minHeight: 72, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  thoughtViewerAuthor: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 12 },
  thoughtViewerHeaderAvatarWrap: { width: 54, height: 54 },
  thoughtViewerOnlineDot: {
    position: 'absolute',
    right: -1,
    bottom: 3,
    width: 17,
    height: 17,
    borderRadius: 9,
    borderWidth: border.thick + border.thin,
    backgroundColor: palette.green[500],
  },
  thoughtViewerAuthorCopy: { flex: 1, minWidth: 0, gap: 2 },
  thoughtViewerName: { fontSize: 21, lineHeight: 27, fontWeight: typography.weight.black, letterSpacing: -0.25 },
  thoughtViewerTime: { fontSize: 15, lineHeight: 21, fontWeight: typography.weight.semibold },
  thoughtViewerHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  thoughtViewerCircleButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 2,
  },
  thoughtViewerMain: { flex: 1, minHeight: 360, alignItems: 'center', justifyContent: 'center', paddingBottom: 28 },
  thoughtViewerBubbleWrap: { alignItems: 'center', marginBottom: 40, paddingBottom: 16 },
  thoughtViewerBubble: {
    minWidth: 150,
    maxWidth: 270,
    minHeight: 66,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 34,
    paddingHorizontal: 28,
    paddingVertical: 17,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 22,
    elevation: 3,
    zIndex: 1,
  },
  thoughtViewerBubbleText: { fontSize: 22, lineHeight: 30, fontWeight: '800', textAlign: 'center', letterSpacing: -0.25 },
  thoughtViewerBubbleTail: {
    position: 'absolute',
    bottom: 5,
    width: 26,
    height: 26,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderRadius: 5,
    transform: [{ rotate: '45deg' }],
  },
  thoughtViewerLargeAvatarFrame: {
    width: 184,
    height: 184,
    borderRadius: 92,
    borderWidth: 6,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.11,
    shadowRadius: 24,
    elevation: 4,
  },
  thoughtViewerBottom: { gap: 22 },
  thoughtViewerReactionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  thoughtViewerReactionChip: {
    flex: 1,
    minWidth: 0,
    minHeight: 58,
    borderRadius: 29,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.055,
    shadowRadius: 16,
    elevation: 2,
  },
  thoughtViewerReactionText: { fontSize: 26, lineHeight: 31 },
  thoughtViewerReplyRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10 },
  thoughtViewerShareButton: {
    width: 58,
    height: 58,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 2,
  },
  thoughtViewerInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 58,
    borderRadius: 29,
    borderWidth: StyleSheet.hairlineWidth,
    paddingLeft: 20,
    paddingRight: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 2,
  },
  thoughtViewerInputText: { flex: 1, minWidth: 0, fontSize: 17, lineHeight: 23, fontWeight: '700' },
  thoughtViewerSmileButton: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  thoughtViewerQuickReactions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  thoughtViewerQuickReaction: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 13,
    elevation: 1,
  },
  thoughtViewerQuickReactionText: { fontSize: 23, lineHeight: 28 },
  reelsRoot: { flex: 1, backgroundColor: '#000000' },
  reelsAnimatedRoot: { flex: 1, backgroundColor: '#000000' },
  reelsBackground: { flex: 1 },
  reelsTopOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 5,
    paddingHorizontal: 16,
  },
  reelsProgressRow: { height: 5, flexDirection: 'row', gap: 6 },
  reelsProgressTrack: {
    flex: 1,
    height: 3,
    borderRadius: radius.round,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.36)',
  },
  reelsProgressFill: { height: '100%', borderRadius: radius.round, backgroundColor: palette.white },
  reelsHeaderRow: { marginTop: 17, minHeight: 50, flexDirection: 'row', alignItems: 'center', gap: 8 },
  reelsIconButton: { width: 38, height: 44, alignItems: 'center', justifyContent: 'center' },
  reelsAvatar: { width: 44, height: 44, borderRadius: 22, borderWidth: 1.2, borderColor: 'rgba(255,255,255,0.88)' },
  reelsAuthorCopy: { flex: 1, minWidth: 0, justifyContent: 'center', gap: 1 },
  reelsAuthorName: { color: palette.white, fontSize: 17, lineHeight: 22, fontWeight: typography.weight.black, letterSpacing: -0.15 },
  reelsPostedAt: { color: 'rgba(255,255,255,0.78)', fontSize: 13, lineHeight: 18, fontWeight: '600' },
  reelsMoreButton: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  reelsStoryPill: {
    alignSelf: 'flex-start',
    marginTop: 12,
    marginLeft: 54,
    minHeight: 34,
    borderRadius: 18,
    paddingLeft: 10,
    paddingRight: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.17)',
  },
  reelsStoryPlus: {
    width: 21,
    height: 21,
    borderRadius: 11,
    borderWidth: 1.2,
    borderStyle: 'dashed',
    borderColor: 'rgba(255,255,255,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reelsStoryText: { color: palette.white, fontSize: typography.size.sm, lineHeight: 19, fontWeight: typography.weight.extraBold },
  reelsGestureLayer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 3,
  },
  reelsHeartBurst: {
    position: 'absolute',
    top: '42%',
    left: 0,
    right: 0,
    zIndex: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reelsCaptionWrap: { position: 'absolute', left: 24, right: 24, top: '35%', zIndex: 4 },
  reelsCaption: {
    color: palette.white,
    fontSize: 27,
    lineHeight: 40,
    fontWeight: typography.weight.black,
    letterSpacing: -0.45,
    textShadowColor: 'rgba(0,0,0,0.42)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 12,
  },
  reelsBottomBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 0,
    zIndex: 6,
    paddingTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  reelsReplyInput: {
    flex: 1,
    minWidth: 0,
    height: 56,
    borderRadius: 28,
    borderWidth: 1.3,
    borderColor: 'rgba(255,255,255,0.36)',
    backgroundColor: 'rgba(0,0,0,0.28)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    gap: 12,
  },
  reelsReplyText: { flex: 1, color: 'rgba(255,255,255,0.72)', fontSize: 16, lineHeight: 22, fontWeight: '600' },
  reelsRoundAction: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1.3,
    borderColor: 'rgba(255,255,255,0.32)',
    backgroundColor: 'rgba(0,0,0,0.32)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reelsCommentsSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 9,
    minHeight: 310,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 18,
    paddingTop: 10,
    backgroundColor: palette.white,
    shadowColor: palette.black,
    shadowOffset: { width: 0, height: -12 },
    shadowOpacity: 0.22,
    shadowRadius: 28,
    elevation: 12,
  },
  reelsCommentsGrabber: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: radius.round,
    backgroundColor: '#D5DAE8',
  },
  reelsCommentsHeader: { minHeight: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  reelsCommentsTitle: { color: palette.navy[800], fontSize: 18, lineHeight: spacing.xl, fontWeight: typography.weight.black, letterSpacing: -0.2 },
  reelsCommentRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, paddingTop: 4 },
  reelsCommentAvatar: { width: 38, height: 38, borderRadius: 19 },
  reelsCommentBubble: { flex: 1, minWidth: 0, borderRadius: 18, paddingHorizontal: 14, paddingVertical: 10, backgroundColor: '#F1F4FB' },
  reelsCommentName: { color: palette.navy[800], fontSize: 13, lineHeight: 18, fontWeight: typography.weight.black },
  reelsCommentText: { marginTop: spacing.xxs, color: palette.slate[600], fontSize: typography.size.sm, lineHeight: typography.lineHeight.sm, fontWeight: typography.weight.semibold },
  reelsCommentInput: {
    marginTop: 18,
    minHeight: 50,
    borderRadius: 25,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: palette.gray[50],
  },
  reelsCommentPlaceholder: { color: '#5E6885', fontSize: 15, lineHeight: 21, fontWeight: '600' },
  shareThoughtScreen: { flex: 1 },
  shareThoughtContent: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 24 },
  shareThoughtHeader: { minHeight: 74, justifyContent: 'center', position: 'relative' },
  shareThoughtCloseButton: {
    position: 'absolute',
    left: -8,
    top: 15,
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shareThoughtTitle: {
    alignSelf: 'center',
    maxWidth: '64%',
    fontSize: 26,
    lineHeight: 32,
    fontWeight: typography.weight.black,
    letterSpacing: -0.35,
    textAlign: 'center',
  },
  shareThoughtTitleCompact: { maxWidth: '60%', fontSize: 22, lineHeight: 28, letterSpacing: -0.25 },
  shareThoughtSubmitButton: {
    position: 'absolute',
    right: 0,
    top: 10,
    width: 98,
    height: 52,
    borderRadius: 26,
    overflow: 'hidden',
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 4,
  },
  shareThoughtSubmitButtonCompact: { width: 88, height: 48, borderRadius: 24, top: 12 },
  shareThoughtSubmitGradient: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  shareThoughtSubmitText: { color: palette.white, fontSize: 17, lineHeight: 23, fontWeight: typography.weight.black },
  shareThoughtMain: { flex: 1, minHeight: 520, alignItems: 'center', justifyContent: 'center', paddingTop: 42, paddingBottom: 56 },
  shareThoughtBubbleWrap: { width: '100%', alignItems: 'center', position: 'relative', paddingBottom: 14, marginBottom: 38 },
  shareThoughtBubble: {
    width: '74%',
    maxWidth: 300,
    minHeight: 92,
    borderRadius: 23,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.09,
    shadowRadius: 22,
    elevation: 3,
    zIndex: 1,
  },
  shareThoughtBubbleTail: {
    position: 'absolute',
    left: '36%',
    bottom: 4,
    width: 24,
    height: 24,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderRadius: 5,
    transform: [{ rotate: '45deg' }],
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 1,
  },
  shareThoughtCaret: { width: 2, height: 34, borderRadius: 1 },
  shareThoughtInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 48,
    paddingVertical: 0,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '600',
  },
  shareThoughtAvatarFrame: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 5,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 20,
    elevation: 5,
  },
  shareThoughtAvatar: { width: 100, height: 100, borderRadius: 50 },
  shareThoughtActions: { marginTop: 56, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'center', gap: 12 },
  thoughtActionChip: {
    minHeight: 54,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 2,
  },
  thoughtActionText: { fontSize: 16, lineHeight: 22, fontWeight: '700' },
  thoughtGifBadge: { width: 32, height: 32, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  thoughtGifText: { color: palette.white, fontSize: typography.size.xs, lineHeight: 15, fontWeight: typography.weight.black },
  thoughtMoodIcon: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  shareThoughtFooter: { alignItems: 'center', gap: 8, paddingHorizontal: 8 },
  shareThoughtHint: { fontSize: 15, lineHeight: 21, fontWeight: '500', textAlign: 'center' },
  shareThoughtPrivacy: { fontSize: 15, lineHeight: 21, fontWeight: '900', textAlign: 'center' },
  createScreen: { flex: 1 },
  createContent: { paddingHorizontal: 18, paddingTop: 22 },
  createHeader: {
    minHeight: 128,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  createCloseButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  createHeaderCopy: { flex: 1, alignItems: 'center', paddingTop: 3, paddingHorizontal: 8 },
  createTitle: { fontSize: typography.size.xl, lineHeight: 34, fontWeight: typography.weight.black, letterSpacing: -0.4, textAlign: 'center' },
  createSubtitle: { marginTop: 7, fontSize: 15, lineHeight: 21, fontWeight: '500', textAlign: 'center' },
  createHeaderSpacer: { width: 44, height: 44 },
  createActionCard: {
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 22,
    overflow: 'hidden',
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.055,
    shadowRadius: 24,
    elevation: 2,
  },
  createActionRow: { minHeight: 86, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center' },
  createActionIconBox: { width: 58, height: 58, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  createActionMain: {
    flex: 1,
    minWidth: 0,
    alignSelf: 'stretch',
    marginLeft: 16,
    marginRight: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    justifyContent: 'center',
    gap: 4,
  },
  createActionTitle: { fontSize: 18, lineHeight: 24, fontWeight: '900', letterSpacing: -0.15 },
  createActionDescription: { fontSize: 14, lineHeight: 20, fontWeight: '600' },
  createSectionCopy: { marginTop: 30, marginBottom: 12, gap: 5 },
  createSectionTitle: { fontSize: 21, lineHeight: 28, fontWeight: '900', letterSpacing: -0.2 },
  createSectionDescription: { fontSize: 15, lineHeight: 21, fontWeight: '500' },
  suggestedContactCard: {
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 22,
    overflow: 'hidden',
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.045,
    shadowRadius: 22,
    elevation: 2,
  },
  suggestedContactRow: { minHeight: 78, paddingLeft: 14, paddingRight: 12, flexDirection: 'row', alignItems: 'center', gap: 14 },
  suggestedAvatarWrap: { width: 54, height: 54 },
  suggestedAvatar: { width: 54, height: 54, borderRadius: 27 },
  suggestedOnlineDot: {
    position: 'absolute',
    right: -1,
    bottom: 3,
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 3,
  },
  suggestedContactMain: {
    flex: 1,
    minWidth: 0,
    alignSelf: 'stretch',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  suggestedContactCopy: { flex: 1, minWidth: 0, gap: 3 },
  suggestedContactName: { fontSize: 17, lineHeight: 23, fontWeight: '900', letterSpacing: -0.15 },
  suggestedContactMeta: { fontSize: 14, lineHeight: 20, fontWeight: '600' },
  suggestedChatButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  body: { flex: 1 },
  header: { minHeight: CHAT_LIST_HEADER_HEIGHT, paddingHorizontal: spacing.lg + spacing.xxs, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  brand: { flex: 1, minWidth: 0 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  headerAction: { borderRadius: 22 },
  searchArea: {
    minHeight: 76,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchInputPressable: { flex: 1 },
  searchInputBox: { flex: 1 },
  searchBox: {
    minHeight: 56,
    borderWidth: border.thin,
    borderRadius: 28,
    paddingHorizontal: 17,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.05,
    shadowRadius: 18,
    elevation: 1,
  },
  searchPlaceholder: { flex: 1, fontSize: 16, lineHeight: 22, fontWeight: '400' },
  searchInput: { flex: 1, minHeight: 50, fontSize: 16, lineHeight: 22, fontWeight: '400', paddingVertical: 0 },
  searchBackButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  cancelButton: { width: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  cancelText: { fontSize: 16, lineHeight: 22, fontWeight: '800' },
  searchTabs: {
    minHeight: 64,
    marginHorizontal: 18,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  searchTab: {
    flex: 1,
    minHeight: 64,
    borderBottomWidth: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  searchTabLabel: { fontSize: 15, lineHeight: 20, fontWeight: '800' },
  searchContent: { paddingHorizontal: 18, paddingTop: 22, gap: 26 },
  searchSection: { gap: 12 },
  searchSectionHeader: { minHeight: 36, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  searchSectionTitle: { flex: 1, fontSize: 18, lineHeight: 24, fontWeight: '900', letterSpacing: -0.2 },
  searchSectionAction: { minHeight: 36, flexDirection: 'row', alignItems: 'center', gap: 2 },
  searchSectionActionText: { fontSize: 15, lineHeight: 20, fontWeight: '800' },
  searchCard: {
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#27375F',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.035,
    shadowRadius: 18,
    elevation: 1,
  },
  connectedPersonRow: { minHeight: 76, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 13 },
  connectedPersonAvatarWrap: { width: 54, height: 54 },
  connectedPersonAvatar: { width: 54, height: 54, borderRadius: 27 },
  connectedPersonOnline: {
    position: 'absolute',
    right: -1,
    bottom: 3,
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: border.thick + border.thin,
    backgroundColor: palette.green[500],
  },
  connectedPersonMain: {
    flex: 1,
    minWidth: 0,
    alignSelf: 'stretch',
    borderBottomWidth: 1,
    justifyContent: 'center',
    gap: 3,
  },
  connectedPersonName: { fontSize: 16, lineHeight: 22, fontWeight: '900', letterSpacing: -0.15 },
  connectedPersonHandle: { fontSize: 13, lineHeight: 18, fontWeight: '600' },
  miniAppRow: { minHeight: 96, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 14 },
  miniAppLogo: { width: 58, height: 58, borderRadius: 14, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  miniAppLogoImage: { width: '100%', height: '100%' },
  miniAppLogoText: { fontSize: 19, lineHeight: 24, fontWeight: '900' },
  miniAppMain: {
    flex: 1,
    minWidth: 0,
    alignSelf: 'stretch',
    borderBottomWidth: 1,
    justifyContent: 'center',
    gap: 4,
  },
  miniAppTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  miniAppName: { flexShrink: 1, fontSize: 16, lineHeight: 22, fontWeight: '900', letterSpacing: -0.15 },
  miniAppCategory: { fontSize: 13, lineHeight: 18, fontWeight: '700' },
  miniAppDescription: { fontSize: 12, lineHeight: 17, fontWeight: '600' },
  miniAppAddButton: { width: 44, height: 44, borderRadius: 14, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  searchEmptyText: { paddingVertical: 20, paddingHorizontal: 18, fontSize: 13, lineHeight: 19, fontWeight: '600', textAlign: 'center' },
  content: { paddingTop: 10 },
  quickContactsScroll: { overflow: 'visible' },
  quickContacts: { paddingHorizontal: 18, paddingTop: 8, gap: 13 },
  quickContact: { width: QUICK_CONTACT_WIDTH, alignItems: 'center', gap: 0 },
  quickAvatarPressable: { alignItems: 'center' },
  thoughtSlot: {
    width: THOUGHT_BUBBLE_WIDTH,
    height: THOUGHT_BUBBLE_HEIGHT + 9,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  thoughtBubbleWrap: {
    width: THOUGHT_BUBBLE_WIDTH,
    alignItems: 'center',
    paddingBottom: 11,
    marginBottom: -THOUGHT_BUBBLE_OVERLAP,
  },
  thoughtBubble: {
    width: THOUGHT_BUBBLE_WIDTH,
    height: THOUGHT_BUBBLE_HEIGHT,
    borderWidth: 1,
    borderRadius: 15,
    paddingHorizontal: 8,
    paddingVertical: 7,
    justifyContent: 'center',
    overflow: 'hidden',
    shadowColor: '#20305C',
    shadowOffset: { width: 0, height: 9 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 4,
  },
  thoughtBubbleText: {
    fontSize: 10.5,
    lineHeight: 14,
    fontWeight: '700',
    textAlign: 'center',
    includeFontPadding: false,
  },
  thoughtTailLarge: {
    position: 'absolute',
    bottom: 3,
    left: 18,
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 1,
    shadowColor: '#20305C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  thoughtTailSmall: {
    position: 'absolute',
    bottom: 0,
    left: 7,
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  quickAvatarOuter: {
    width: QUICK_AVATAR_SIZE,
    height: QUICK_AVATAR_SIZE,
    borderRadius: QUICK_AVATAR_SIZE / 2,
    borderWidth: 1.5,
    borderColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 2,
  },
  quickName: { width: QUICK_CONTACT_WIDTH, marginTop: 8, textAlign: 'center', fontSize: 14, lineHeight: 20, fontWeight: '600' },
  onlineDotLarge: { position: 'absolute', right: 0, bottom: 7, width: 17, height: 17, borderRadius: 8.5, borderWidth: border.thick + border.thin, backgroundColor: palette.green[500] },
  conversationList: { marginTop: 18 },
  conversationRow: { minHeight: 80, marginHorizontal: 18, paddingVertical: 12, flexDirection: 'row', alignItems: 'center', gap: 13 },
  avatarWrap: { width: LIST_AVATAR_SIZE, height: LIST_AVATAR_SIZE },
  onlineDot: { position: 'absolute', right: -1, bottom: 3, width: 16, height: 16, borderRadius: 8, borderWidth: border.thick + border.thin, backgroundColor: palette.green[500] },
  muteBadge: {
    position: 'absolute',
    left: -3,
    bottom: 2,
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  conversationMain: { flex: 1, minWidth: 0, gap: 5 },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  conversationName: { flexShrink: 1, fontSize: 17, lineHeight: 23, fontWeight: '700', letterSpacing: -0.2 },
  unreadName: { fontWeight: '900' },
  previewRow: { minHeight: 24, flexDirection: 'row', alignItems: 'center', gap: 8 },
  previewMain: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 6 },
  conversationMessage: { flexShrink: 1, fontSize: 14, lineHeight: 20, fontWeight: '500' },
  unreadMessage: { fontWeight: '800' },
  mediaOnlyText: { fontWeight: '800' },
  groupSender: { maxWidth: 58, fontSize: 12, lineHeight: 17, fontWeight: '700' },
  mediaThumbStack: { flexDirection: 'row', alignItems: 'center', paddingRight: 1 },
  mediaThumb: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  mediaThumbOverlap: { marginLeft: -8 },
  mediaThumbImage: { width: '100%', height: '100%' },
  gifThumbText: { fontSize: 8, lineHeight: 10, fontWeight: '900' },
  mediaThumbOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.56)',
  },
  mediaThumbOverlayText: { color: '#FFFFFF', fontSize: 9, lineHeight: 11, fontWeight: '900' },
  trailing: { width: 70, alignItems: 'flex-end', gap: 9 },
  timeStatusRow: { minHeight: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 3 },
  timeText: { fontSize: 12, lineHeight: 17, fontWeight: '600' },
  unreadDot: { width: 11, height: 11, borderRadius: 6, backgroundColor: '#0B63FF' },
  unreadCount: { minWidth: 22, height: 22, borderRadius: 11, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 5 },
  unreadCountText: { color: '#FFFFFF', fontSize: 11, lineHeight: 14, fontWeight: '900' },
  identraAvatar: { alignItems: 'center', justifyContent: 'center' },
  initialAvatar: { alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  initials: { position: 'absolute', fontWeight: '900' },
  groupInitials: { color: '#FFFFFF', fontWeight: '900', letterSpacing: -0.5 },
  emptyState: { minHeight: 230, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 28 },
  emptyIcon: { width: 68, height: 68, borderRadius: 34, alignItems: 'center', justifyContent: 'center' },
  emptyTitle: { marginTop: 15, fontSize: 17, lineHeight: 23, fontWeight: '800', textAlign: 'center' },
  emptyDescription: { marginTop: 7, fontSize: 13, lineHeight: 19, fontWeight: '500', textAlign: 'center' },
  bottomMenu: {
    minHeight: layout.bottomNavHeight,
    borderTopWidth: border.thin,
    paddingTop: 7,
    paddingHorizontal: 6,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  bottomMenuItem: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'flex-start', gap: 2 },
  bottomMenuIcon: { width: 29, height: 29, alignItems: 'center', justifyContent: 'center' },
  bottomMenuLabel: { fontSize: 11, lineHeight: 14, fontWeight: typography.weight.semibold, textAlign: 'center' },
});
