import { StyleSheet } from 'react-native';
import { border, palette, radius, spacing, touchTarget, typography } from '../../../theme';

export const newsFeedSearchStyles = StyleSheet.create({
  screen: { flex: 1 },
  searchHeader: {
    minHeight: 72,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  backButton: {
    width: touchTarget.minimum,
    height: touchTarget.minimum,
    borderRadius: radius.round,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchBox: {
    flex: 1,
    minWidth: 0,
    height: 50,
    borderRadius: radius.md,
    borderWidth: border.hairline,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 0,
    fontSize: typography.size.sm,
    lineHeight: typography.lineHeight.sm,
    fontWeight: typography.weight.medium,
  },
  filterButton: {
    width: 50,
    height: 50,
    borderRadius: radius.md,
    borderWidth: border.hairline,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabs: {
    minHeight: 52,
    borderBottomWidth: border.hairline,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  tab: {
    flex: 1,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: spacing.md,
    position: 'relative',
  },
  tabText: { fontSize: typography.size.xs + 1, fontWeight: typography.weight.black },
  activeTabText: { fontWeight: typography.weight.black },
  tabIndicator: { position: 'absolute', bottom: 0, width: '72%', height: 3, borderTopLeftRadius: 2, borderTopRightRadius: 2 },
  content: { paddingHorizontal: spacing.md, paddingTop: spacing.lg, gap: spacing.lg },
  section: { gap: spacing.sm },
  sectionHeader: { minHeight: 32, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md },
  sectionTitle: { fontSize: typography.size.md + 1, lineHeight: 23, fontWeight: typography.weight.black },
  viewAllButton: { minHeight: touchTarget.minimum, flexDirection: 'row', alignItems: 'center', gap: spacing.xxs },
  viewAllText: { fontSize: typography.size.xs + 1, fontWeight: typography.weight.black },
  endOfContent: {
    minHeight: 56,
    paddingHorizontal: spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
  },
  endLine: { flex: 1, height: border.hairline },
  endText: { fontSize: typography.size.xs, lineHeight: typography.lineHeight.xs, fontWeight: typography.weight.semibold },
  modalLayer: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  filterSheet: {
    maxHeight: '86%',
    borderTopLeftRadius: radius.xxl,
    borderTopRightRadius: radius.xxl,
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.lg,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 46,
    height: 5,
    borderRadius: radius.round,
    marginBottom: spacing.md,
    opacity: 0.86,
  },
  filterHeader: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  filterTitleGroup: {
    flex: 1,
    minWidth: 0,
  },
  filterTitle: {
    fontSize: typography.size.xl,
    lineHeight: typography.lineHeight.xl,
    fontWeight: typography.weight.black,
  },
  filterSubtitle: {
    marginTop: spacing.xxs,
    fontSize: typography.size.xs,
    lineHeight: typography.lineHeight.xs,
    fontWeight: typography.weight.medium,
  },
  resetButton: {
    minHeight: touchTarget.minimum,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.xs,
  },
  resetText: {
    fontSize: typography.size.sm,
    lineHeight: typography.lineHeight.sm,
    fontWeight: typography.weight.black,
  },
  filterBody: {
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
    gap: spacing.xl,
  },
  filterSection: {
    gap: spacing.md,
  },
  filterSectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  filterSectionTitle: {
    fontSize: typography.size.md + 1,
    lineHeight: 24,
    fontWeight: typography.weight.black,
  },
  optionGrid: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  optionButton: {
    flex: 1,
    minWidth: 0,
    minHeight: 54,
    borderRadius: radius.md,
    borderWidth: border.hairline,
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  optionButtonText: {
    minWidth: 0,
    flexShrink: 1,
    fontSize: typography.size.xs + 1,
    lineHeight: typography.lineHeight.xs,
    fontWeight: typography.weight.black,
    textAlign: 'center',
  },
  dateField: {
    minHeight: 64,
    borderRadius: radius.md,
    borderWidth: border.hairline,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  dateCopy: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xxs,
  },
  dateLabel: {
    fontSize: typography.size.xs,
    lineHeight: typography.lineHeight.xs,
    fontWeight: typography.weight.medium,
  },
  dateValue: {
    fontSize: typography.size.md,
    lineHeight: typography.lineHeight.md,
    fontWeight: typography.weight.semibold,
  },
  interestSearchBox: {
    minHeight: 52,
    borderRadius: radius.md,
    borderWidth: border.hairline,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  interestInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 0,
    fontSize: typography.size.sm,
    lineHeight: typography.lineHeight.sm,
    fontWeight: typography.weight.medium,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  interestChip: {
    minHeight: touchTarget.minimum,
    maxWidth: '100%',
    borderRadius: radius.md,
    borderWidth: border.hairline,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  interestChipText: {
    minWidth: 0,
    flexShrink: 1,
    fontSize: typography.size.xs + 1,
    lineHeight: typography.lineHeight.xs,
    fontWeight: typography.weight.black,
  },
  filterHint: {
    fontSize: typography.size.xs,
    lineHeight: typography.lineHeight.xs,
    fontWeight: typography.weight.medium,
  },
  filterFooter: {
    paddingTop: spacing.md,
    flexDirection: 'row',
    gap: spacing.md,
  },
  footerButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: radius.md,
    overflow: 'hidden',
  },
  cancelFilterButton: {
    borderWidth: border.thin,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelFilterText: {
    fontSize: typography.size.md,
    lineHeight: typography.lineHeight.md,
    fontWeight: typography.weight.black,
  },
  applyFilterButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyFilterText: {
    color: palette.white,
    fontSize: typography.size.md,
    lineHeight: typography.lineHeight.md,
    fontWeight: typography.weight.black,
  },
  sectionList: {
    borderWidth: border.hairline,
    borderRadius: radius.xl,
    overflow: 'hidden',
  },
  row: {
    minHeight: 82,
    borderBottomWidth: border.hairline,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  trendCopy: { flex: 1, minWidth: 0, gap: spacing.xxs },
  suggestionCopy: { flex: 1, minWidth: 0, gap: spacing.xxs },
  inlineTitle: { minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  itemTitle: { minWidth: 0, flexShrink: 1, fontSize: typography.size.sm + 1, lineHeight: 20, fontWeight: typography.weight.black },
  itemMeta: { fontSize: typography.size.xs, lineHeight: typography.lineHeight.xs, fontWeight: typography.weight.medium },
  itemDescription: { fontSize: typography.size.xs, lineHeight: typography.lineHeight.xs, fontWeight: typography.weight.medium },
  verifiedBadge: { width: 17, height: 17, flexShrink: 0 },
  approvedBadge: { width: 14, height: 14, flexShrink: 0 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  accountAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.gray[100],
  },
  fallbackAvatarText: { color: palette.white, fontSize: typography.size.lg, fontWeight: typography.weight.black },
  squareAvatar: {
    width: 52,
    height: 52,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.gray[100],
  },
  outlineButton: {
    minWidth: 72,
    minHeight: 36,
    borderRadius: radius.sm,
    borderWidth: border.hairline,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outlineButtonText: { fontSize: typography.size.xs + 1, fontWeight: typography.weight.black },
  moreButton: {
    width: touchTarget.minimum,
    height: touchTarget.minimum,
    borderRadius: radius.round,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: -spacing.sm,
  },
  sparkline: {
    width: 92,
    height: 52,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    gap: 2,
    paddingRight: spacing.xs,
  },
  sparkBar: { width: 5, borderRadius: 3 },
  sparkDot: { position: 'absolute', right: 0, top: 5, width: 9, height: 9, borderRadius: 5 },
});
