import { StyleSheet } from 'react-native';
import { border, componentSize, palette, radius, spacing, touchTarget, typography } from '../../theme';
export const styles = StyleSheet.create({
  detailScreenContent: { gap: spacing.md, paddingBottom: spacing.xl + spacing.xs + spacing.xxs },
  detailShareButton: { minHeight: 44, borderRadius: radius.md, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.xs + spacing.xxs },
  detailShareText: { fontSize: 13, fontWeight: typography.weight.extraBold },
  detailStatusIntro: { alignItems: 'flex-start', gap: 7, marginTop: -2, marginBottom: 2 },
  detailStatusPill: { minHeight: 27, borderRadius: radius.md + 2, paddingHorizontal: spacing.sm + spacing.xxs, flexDirection: 'row', alignItems: 'center', gap: spacing.xs + spacing.xxs },
  detailStatusText: { fontSize: typography.size.xs, fontWeight: typography.weight.extraBold },
  detailStatusDescription: { fontSize: typography.size.xs, lineHeight: spacing.lg + spacing.xxs, fontWeight: typography.weight.semibold },
  detailCredentialCard: { borderWidth: border.thin, borderRadius: radius.lg + 2, padding: spacing.lg },
  detailCredentialTop: { minHeight: 91, flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  detailCredentialMain: { flex: 1, gap: spacing.xs },
  detailCredentialTitle: { fontSize: 19, fontWeight: typography.weight.black },
  detailCredentialIssuer: { fontSize: 13, fontWeight: typography.weight.semibold },
  detailCategoryPill: { alignSelf: 'flex-start', borderRadius: radius.md, paddingHorizontal: spacing.sm, minHeight: spacing.xl, flexDirection: 'row', alignItems: 'center', gap: spacing.xs + 1 },
  detailCategoryText: { fontSize: 11, fontWeight: typography.weight.bold },
  detailShieldArt: { width: 59, height: 68, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  detailDateGrid: { marginTop: spacing.md + spacing.xxs, marginBottom: spacing.md + spacing.xxs, paddingVertical: spacing.md + 1, borderTopWidth: border.thin, borderBottomWidth: border.thin, flexDirection: 'row' },
  detailDateColumn: { flex: 1, paddingHorizontal: 2, gap: 7, borderLeftWidth: 0 },
  detailDateColumnDivider: { borderLeftWidth: border.thin, paddingLeft: spacing.md + spacing.xxs },
  detailMetaLabel: { fontSize: 11, fontWeight: typography.weight.semibold },
  detailMetaValueRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  detailMetaValue: { fontSize: typography.size.xs, fontWeight: typography.weight.extraBold, flexShrink: 1 },
  detailIdRow: { minHeight: 35, flexDirection: 'row', alignItems: 'center', gap: 8 },
  detailIdValue: { flex: 1, fontSize: typography.size.xs, fontWeight: typography.weight.extraBold },
  detailIssuerCard: { padding: 14, gap: 13 },
  detailCardHeading: { fontSize: 13, fontWeight: typography.weight.black },
  detailIssuerRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  detailIssuerLogo: { width: 52, height: 52, borderRadius: 26, borderWidth: border.thin, alignItems: 'center', justifyContent: 'center' },
  detailIssuerMain: { flex: 1 },
  detailIssuerNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  detailIssuerName: { flexShrink: 1, fontSize: 13, fontWeight: typography.weight.black },
  detailIssuerDescription: { marginTop: 4, fontSize: 11, lineHeight: 17, fontWeight: '600' },
  detailSectionTitle: { marginTop: spacing.xs + spacing.xxs, fontSize: 15, fontWeight: typography.weight.black },
  detailAttributeCard: { paddingVertical: 6 },
  detailAttributeRow: { minHeight: 47, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16 },
  detailAttributeLabel: { flex: 1, fontSize: 12, fontWeight: '600' },
  detailAttributeValue: { flex: 1.35, fontSize: 12, lineHeight: 17, fontWeight: '700', textAlign: 'right' },
  detailAttributeHighlight: { borderRadius: radius.md, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs - 1, backgroundColor: palette.green[100] },
  detailAttributeHighlightText: { fontSize: typography.size.xs, fontWeight: typography.weight.extraBold },
  detailActionCard: { minHeight: 68, borderRadius: radius.lg, borderWidth: border.thin, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: 11 },
  detailActionIcon: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  detailActionMain: { flex: 1 },
  detailActionTitle: { fontSize: 13, fontWeight: typography.weight.black },
  detailActionDescription: { marginTop: 3, fontSize: 11, lineHeight: 16, fontWeight: '600' },
  contractDetailScreenContent: { gap: spacing.md, paddingBottom: spacing.xl },
  contractHeaderShield: { width: 44, height: 44, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' },
  contractHeroCard: { borderWidth: border.thin, borderRadius: radius.lg + 2, padding: spacing.md, gap: spacing.md },
  contractHeroTop: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  contractTicketArt: {
    width: 118,
    height: 128,
    borderRadius: radius.lg,
    backgroundColor: '#172B76',
    overflow: 'hidden',
    padding: spacing.md,
    justifyContent: 'center',
  },
  contractTicketSmall: { position: 'absolute', top: 11, left: 12, color: 'rgba(255,255,255,0.78)', fontSize: 8, fontWeight: typography.weight.bold },
  contractTicketBrand: { color: palette.white, fontSize: 21, lineHeight: 25, fontWeight: typography.weight.black, letterSpacing: -0.7 },
  contractTicketYear: { color: 'rgba(255,255,255,0.9)', fontSize: 18, lineHeight: 22, fontWeight: typography.weight.medium, letterSpacing: 2 },
  contractTicketDate: { position: 'absolute', left: 13, bottom: 12, color: 'rgba(255,255,255,0.86)', fontSize: 9, fontWeight: typography.weight.bold },
  contractHeroMain: { flex: 1, minWidth: 0, gap: 7 },
  contractTitleRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  contractTicketTitle: { flex: 1, minWidth: 0, fontSize: 19, lineHeight: 24, fontWeight: typography.weight.black },
  contractVerifiedBadge: { width: 18, height: 18, flexShrink: 0 },
  contractTicketSubtitle: { fontSize: typography.size.md, lineHeight: typography.lineHeight.md, fontWeight: typography.weight.medium },
  contractMetaLine: { minHeight: 22, flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  contractMetaLabel: { fontSize: 12, fontWeight: typography.weight.semibold },
  contractMetaValue: { flex: 1, minWidth: 0, fontSize: 12, fontWeight: typography.weight.extraBold },
  contractHeroFooter: { borderTopWidth: border.thin, paddingTop: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm },
  contractBelongsRow: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  contractBelongsText: { flex: 1, minWidth: 0, fontSize: 13, lineHeight: 18, fontWeight: typography.weight.semibold },
  contractStateBadge: { minHeight: 34, borderRadius: radius.md + 2, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  contractStateBadgeText: { fontSize: 12, fontWeight: typography.weight.extraBold },
  contractSectionTitle: { marginTop: spacing.xs, fontSize: typography.size.lg - 2, lineHeight: 24, fontWeight: typography.weight.black },
  contractTableCard: { borderWidth: border.thin, borderRadius: radius.lg, overflow: 'hidden' },
  contractTableRow: { minHeight: 48, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  contractTableLabel: { flex: 1, minWidth: 0, fontSize: 13, lineHeight: 18, fontWeight: typography.weight.semibold },
  contractTableValue: { flex: 1, minWidth: 0, textAlign: 'right', fontSize: 13, lineHeight: 18, fontWeight: typography.weight.extraBold },
  contractFlowCard: { borderWidth: border.thin, borderRadius: radius.lg, padding: spacing.md, gap: spacing.md },
  contractFlowPanel: { borderWidth: border.thin, borderRadius: radius.md + 2, padding: spacing.md, gap: spacing.sm },
  contractFlowTitleRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  contractFlowTitle: { fontSize: 13, lineHeight: 18, fontWeight: typography.weight.black },
  contractFlowInner: { minHeight: 80, borderWidth: border.thin, borderRadius: radius.md, padding: spacing.sm, flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  contractFlowTicketIcon: { width: 52, height: 52, borderRadius: radius.md, backgroundColor: palette.blue[700], alignItems: 'center', justifyContent: 'center' },
  contractPayIcon: { width: 52, height: 52, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' },
  contractFlowCopy: { flex: 1, minWidth: 0 },
  contractFlowItemTitle: { fontSize: 13, lineHeight: 18, fontWeight: typography.weight.black },
  contractFlowItemMeta: { marginTop: 2, fontSize: 11, lineHeight: 15, fontWeight: typography.weight.semibold },
  contractFlowSwap: { alignSelf: 'center', width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  contractIssuerCard: { minHeight: 76, borderWidth: border.thin, borderRadius: radius.lg, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  contractIssuerLogo: { width: 54, height: 54, borderRadius: 27, backgroundColor: '#3B00E8', alignItems: 'center', justifyContent: 'center' },
  contractIssuerLogoText: { color: palette.white, fontSize: 10, fontWeight: typography.weight.black, letterSpacing: -0.4 },
  contractIssuerMain: { flex: 1, minWidth: 0 },
  contractIssuerNameRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  contractIssuerName: { flexShrink: 1, minWidth: 0, fontSize: 14, lineHeight: 19, fontWeight: typography.weight.black },
  contractIssuerBadge: { width: 15, height: 15 },
  contractIssuerDescription: { marginTop: 3, fontSize: 11.5, lineHeight: 16, fontWeight: typography.weight.semibold },
  contractDetailActions: { flexDirection: 'row', gap: spacing.sm },
  contractDetailSecondaryButton: { flex: 1, minHeight: 50, borderWidth: border.thin, borderRadius: radius.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs },
  contractDetailPrimaryButton: { flex: 1, minHeight: 50, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' },
  contractDetailSecondaryText: { fontSize: typography.size.sm, fontWeight: typography.weight.black },
  contractDetailPrimaryText: { color: palette.white, fontSize: typography.size.sm, fontWeight: typography.weight.black },
  shareScreenContent: { paddingTop: 8, paddingBottom: 26, gap: 14 },
  shareStatusIntro: { alignItems: 'flex-start', gap: 7, marginTop: -2, marginBottom: 2 },
  shareVerifiedPill: { alignSelf: 'flex-start', minHeight: 27, borderRadius: radius.md + 2, paddingHorizontal: spacing.sm + spacing.xxs, flexDirection: 'row', alignItems: 'center', gap: spacing.xs + spacing.xxs, backgroundColor: palette.green[100] },
  shareVerifiedText: { fontSize: typography.size.xs, fontWeight: typography.weight.extraBold },
  shareStatusDescription: { fontSize: 12, lineHeight: 18, fontWeight: '600' },
  shareCredentialCard: { borderWidth: border.thin, borderRadius: radius.lg + 2, padding: spacing.md + spacing.xxs },
  shareCredentialTop: { minHeight: 96, flexDirection: 'row', alignItems: 'center', gap: 12 },
  shareCredentialMain: { flex: 1, minWidth: 0 },
  shareCredentialTitle: { fontSize: 18, lineHeight: 23, fontWeight: typography.weight.black },
  shareCredentialIssuer: { marginTop: 4, fontSize: 12, lineHeight: 17, fontWeight: '600' },
  shareCategory: { alignSelf: 'flex-start', minHeight: 23, marginTop: 7, borderRadius: 12, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', gap: 5 },
  shareCategoryText: { fontSize: 11, fontWeight: '700' },
  shareShieldArt: { width: 58, height: 66, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  shareMetaGrid: { marginTop: 13, paddingTop: 13, borderTopWidth: 1, flexDirection: 'row' },
  shareMetaItem: { flex: 1, minWidth: 0, minHeight: 49, paddingHorizontal: 4, justifyContent: 'center', gap: 7 },
  shareMetaDivider: { borderLeftWidth: 1, paddingLeft: 10 },
  shareMetaLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  shareMetaLabel: { fontSize: 9.5, lineHeight: 13, fontWeight: '600' },
  shareMetaValue: { flexShrink: 1, minWidth: 0, fontSize: 10.5, lineHeight: 15, fontWeight: '800' },
  shareIdRow: { minWidth: 0, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start', gap: 4 },
  shareSectionHeader: { marginTop: 5, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  shareSectionTitle: { fontSize: 15, fontWeight: '900' },
  shareSelectedCount: { fontSize: 13, fontWeight: '800' },
  shareInfo: { borderRadius: 15, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 10 },
  shareInfoText: { flex: 1, fontSize: 11, lineHeight: 17, fontWeight: '600' },
  shareFieldList: { borderWidth: border.thin, borderRadius: radius.lg + 2, paddingHorizontal: spacing.md + spacing.xxs, overflow: 'hidden' },
  shareFieldRow: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 12 },
  shareFieldIcon: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  shareFieldMain: { flex: 1, minWidth: 0 },
  shareFieldLabel: { fontSize: 13, lineHeight: 17, fontWeight: '900' },
  shareFieldValue: { marginTop: 3, fontSize: 12, lineHeight: 16, fontWeight: '600' },
  shareCheckbox: { width: 25, height: 25, borderRadius: radius.xs - 1, borderWidth: border.medium, alignItems: 'center', justifyContent: 'center' },
  shareWarning: { borderWidth: border.thin, borderColor: '#FFD4D6', borderRadius: radius.lg, padding: spacing.md + spacing.xxs, flexDirection: 'row', alignItems: 'flex-start', gap: 11, backgroundColor: '#FFF7F7' },
  shareWarningText: { flex: 1, color: '#F0444C', fontSize: 11, lineHeight: 18, fontWeight: typography.weight.bold },
  shareActions: { flexDirection: 'row', gap: 10 },
  shareCancelButton: { flex: 1, minHeight: 52, borderWidth: border.thin, borderRadius: radius.md + 2, alignItems: 'center', justifyContent: 'center' },
  shareCancelText: { fontSize: 14, fontWeight: '900' },
  shareSubmitButton: { flex: 1.05, minHeight: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  shareSubmitText: { color: palette.white, fontSize: typography.size.sm, fontWeight: typography.weight.black },
  shareEncryption: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, paddingHorizontal: 12 },
  shareEncryptionText: { flexShrink: 1, fontSize: 10.5, lineHeight: 15, fontWeight: '600', textAlign: 'center' },
  shareQrScreenContent: { paddingTop: 4, paddingBottom: 30, gap: 15 },
  shareQrBrandHeader: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 7 },
  shareQrBrand: { flex: 1, fontSize: typography.size.lg, fontWeight: typography.weight.black, letterSpacing: -0.4 },
  shareQrHeaderSpacer: { width: 44, height: 44 },
  shareQrSubtitle: { marginTop: -5, fontSize: 13, lineHeight: 19, fontWeight: '500' },
  shareQrCard: { borderWidth: border.thin, borderRadius: radius.lg + 3, padding: spacing.lg, alignItems: 'center' },
  connectionQrCard: { paddingTop: 3 },
  shareQrVerified: { minHeight: 28, borderRadius: radius.md + 2, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: spacing.xs + spacing.xxs, backgroundColor: palette.green[100] },
  shareQrVerifiedText: { fontSize: typography.size.xs, fontWeight: typography.weight.extraBold },
  shareQrCredentialTitle: { marginTop: 11, fontSize: 23, lineHeight: 28, fontWeight: typography.weight.black, textAlign: 'center' },
  shareQrIssuer: { marginTop: 5, fontSize: 14, lineHeight: 20, fontWeight: '600', textAlign: 'center' },
  shareQrDidRow: { maxWidth: '88%', marginTop: 6, minHeight: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 },
  shareQrDid: { flexShrink: 1, fontSize: 12, lineHeight: 17, fontWeight: '600' },
  shareQrCodeFrame: { marginTop: 13, width: 278, height: 278, borderRadius: radius.xl, backgroundColor: palette.white, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  shareQrLogo: { position: 'absolute', width: 52, height: 58, borderRadius: radius.lg, backgroundColor: '#4A6CFF', borderWidth: 5, borderColor: palette.white, alignItems: 'center', justifyContent: 'center' },
  shareQrExpired: { width: '78%', alignItems: 'center', gap: spacing.sm },
  shareQrExpiredTitle: { fontSize: 17, lineHeight: 22, fontWeight: typography.weight.black, textAlign: 'center' },
  shareQrExpiredText: { fontSize: 12, lineHeight: 18, fontWeight: '600', textAlign: 'center' },
  shareQrExpiry: { marginTop: 12, minHeight: 39, borderRadius: 20, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 6 },
  shareQrExpiryText: { fontSize: 11.5, fontWeight: '600' },
  shareQrExpiryTime: { fontSize: typography.size.xs, fontWeight: typography.weight.black },
  shareQrActions: { flexDirection: 'row', gap: 8 },
  shareQrAction: { flex: 1, minWidth: 0, alignItems: 'center', paddingVertical: 4 },
  shareQrActionIcon: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center' },
  shareQrActionTitle: { marginTop: spacing.sm, fontSize: 13, lineHeight: 18, fontWeight: typography.weight.black, textAlign: 'center' },
  shareQrActionDescription: { marginTop: 2, fontSize: 10.5, lineHeight: 15, fontWeight: '600', textAlign: 'center' },
  shareQrSafetyCard: { minHeight: 104, borderWidth: border.thin, borderRadius: radius.lg + 2, padding: spacing.md + spacing.xxs, flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  shareQrSafetyIcon: { width: 58, height: 66, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  shareQrSafetyMain: { flex: 1, minWidth: 0 },
  shareQrSafetyTitle: { fontSize: 13, lineHeight: 18, fontWeight: typography.weight.black },
  shareQrSafetyText: { marginTop: 5, fontSize: 10.5, lineHeight: 16, fontWeight: '600' },
  shareQrCancelCard: { minHeight: 85, borderWidth: border.thin, borderColor: '#FFD4D6', borderRadius: radius.lg + 2, padding: spacing.md + spacing.xxs, flexDirection: 'row', alignItems: 'center', gap: spacing.md, backgroundColor: '#FFF8F8' },
  shareQrCancelText: { flex: 1, color: '#F0444C', fontSize: typography.size.xs, lineHeight: 19, fontWeight: typography.weight.extraBold },
  profileHero: { alignItems: 'center' },
  profileAvatar: { width: 76, height: 76, borderRadius: 25, alignItems: 'center', justifyContent: 'center' },
  profileName: { marginTop: 11, fontSize: 21, fontWeight: typography.weight.black },
  profileDid: { marginTop: 4, fontSize: 12 },
  formCard: { gap: spacing.md + spacing.xxs },
  field: { gap: spacing.xs + spacing.xxs },
  fieldLabel: { fontSize: typography.size.xs, fontWeight: typography.weight.bold },
  inputWrap: { minHeight: 50, borderWidth: border.thin, borderRadius: radius.md + 1, paddingLeft: 13, flexDirection: 'row', alignItems: 'center', gap: spacing.sm + spacing.xxs },
  input: { flex: 1, minHeight: componentSize.inputHeight, fontSize: typography.size.md, paddingRight: spacing.md },
  securityScore: { flexDirection: 'row', alignItems: 'center', gap: 13 },
  securityScoreIcon: { width: 58, height: 58, borderRadius: 29, backgroundColor: palette.green[100], alignItems: 'center', justifyContent: 'center' },
  securityMain: { flex: 1 },
  securityTitle: { fontSize: typography.size.md, fontWeight: typography.weight.black },
  securityText: { fontSize: 12, lineHeight: 18, marginTop: 4 },
  settingsCard: { paddingVertical: 0 },
  settingRow: { minHeight: 79, flexDirection: 'row', alignItems: 'center', gap: 12 },
  settingIcon: { width: 44, height: 44, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  settingMain: { flex: 1 },
  settingTitle: { fontSize: typography.size.sm, fontWeight: typography.weight.extraBold },
  settingDescription: { fontSize: 11, lineHeight: 16, marginTop: 3 },
  notificationScreenContent: { paddingTop: spacing.md, paddingBottom: 36, gap: spacing.lg },
  notificationHeader: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  notificationScreenTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: typography.size.xl,
    lineHeight: typography.lineHeight.xl,
    fontWeight: typography.weight.black,
    letterSpacing: -0.9,
  },
  markReadButton: { minHeight: touchTarget.minimum, justifyContent: 'center', paddingHorizontal: spacing.xs },
  markReadText: { fontSize: typography.size.sm, lineHeight: typography.lineHeight.sm, fontWeight: typography.weight.black },
  notificationTabs: {
    minHeight: 56,
    paddingRight: spacing.md,
    borderBottomWidth: border.hairline,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.sm,
  },
  notificationTab: {
    minHeight: 48,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
    paddingTop: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  notificationTabText: { fontSize: typography.size.sm, lineHeight: typography.lineHeight.sm, fontWeight: typography.weight.black },
  notificationTabCount: {
    minWidth: 26,
    height: 26,
    borderRadius: 13,
    paddingHorizontal: spacing.xs,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationTabCountText: { fontSize: typography.size.xs, lineHeight: typography.lineHeight.xs, fontWeight: typography.weight.black },
  notificationTabUnderline: { position: 'absolute', bottom: -1, right: 0, left: 0, height: 3, borderTopLeftRadius: 2, borderTopRightRadius: 2 },
  notificationList: { gap: spacing.none },
  notificationRow: {
    minHeight: 116,
    paddingVertical: spacing.lg,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  notificationAvatarWrap: { width: 64, height: 64, flexShrink: 0 },
  notificationAvatarImage: { width: 58, height: 58, borderRadius: 29, backgroundColor: palette.gray[100] },
  notificationAvatarTextBox: { width: 58, height: 58, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  notificationAvatarText: { fontSize: typography.size.md, fontWeight: typography.weight.black, letterSpacing: -0.3 },
  notificationBadgeIcon: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 29,
    height: 29,
    borderRadius: 15,
    borderWidth: border.medium,
    borderColor: palette.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationMain: { flex: 1, minWidth: 0, paddingTop: spacing.xxs },
  notificationTitle: { fontSize: typography.size.md, lineHeight: 23, fontWeight: typography.weight.regular },
  notificationTitleStrong: { fontWeight: typography.weight.black },
  notificationBody: { marginTop: spacing.xs, fontSize: typography.size.sm, lineHeight: typography.lineHeight.sm, fontWeight: typography.weight.medium },
  notificationChip: {
    alignSelf: 'flex-start',
    maxWidth: '100%',
    minHeight: 34,
    marginTop: spacing.md,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  notificationChipText: { flexShrink: 1, fontSize: typography.size.xs + 1, lineHeight: typography.lineHeight.xs, fontWeight: typography.weight.medium },
  notificationTrailing: { width: 82, minHeight: 84, alignItems: 'flex-end', justifyContent: 'space-between' },
  notificationTrailingTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: spacing.xs },
  notificationTime: { flex: 1, minWidth: 0, fontSize: typography.size.xs + 1, lineHeight: typography.lineHeight.xs, fontWeight: typography.weight.semibold, textAlign: 'right' },
  notificationUnreadDot: { width: 9, height: 9, borderRadius: 5, marginRight: spacing.sm, marginBottom: spacing.sm },
  notificationEnd: { marginTop: spacing.lg, paddingHorizontal: spacing.xxl, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm },
  notificationEndLine: { flex: 1, height: border.hairline },
  notificationEndIcon: { width: 28, height: 28, borderRadius: 14, borderWidth: border.hairline, alignItems: 'center', justifyContent: 'center' },
  notificationEndText: { textAlign: 'center', fontSize: typography.size.xs, lineHeight: typography.lineHeight.xs, fontWeight: typography.weight.medium },
});
