import { StyleSheet } from 'react-native';
import { border, componentSize, palette, radius, spacing, typography } from '../../theme';

export const settingsStyles = StyleSheet.create({
  activityScreenContent: { paddingTop: spacing.xxs, paddingBottom: spacing.xl, gap: spacing.md + 1 },
  activityBrandHeader: { minHeight: componentSize.buttonHeight, flexDirection: 'row', alignItems: 'center', gap: spacing.sm - 1 },
  activityHeaderButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  activityBrandLogo: { flex: 1 },
  activityTitleRow: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: spacing.sm + spacing.xxs, paddingHorizontal: spacing.xs },
  activityTitleText: { flex: 1 },
  activityScreenTitle: { fontSize: typography.size.lg + 2, fontWeight: typography.weight.extraBold, letterSpacing: -0.45 },
  activityIntro: { marginTop: spacing.xs - 1, fontSize: typography.size.xs, lineHeight: typography.lineHeight.xs },
  activityFilterButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    borderWidth: border.thin,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xxs,
  },
  activityFilterButtonText: { fontSize: 10, fontWeight: typography.weight.medium },
  activityFilterCount: {
    position: 'absolute',
    right: -1,
    top: -1,
    width: 17,
    height: 17,
    borderRadius: 9,
    backgroundColor: palette.blue[700],
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityFilterCountText: { color: palette.white, fontSize: 9, fontWeight: typography.weight.extraBold },
  activitySummary: { flexDirection: 'row', gap: spacing.sm - 1 },
  activitySummaryCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 126,
    borderWidth: border.thin,
    borderRadius: radius.lg - 1,
    paddingHorizontal: 3,
    paddingVertical: 12,
    alignItems: 'center',
  },
  activitySummaryIcon: { width: 36, height: 36, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' },
  activitySummaryLabel: { marginTop: spacing.sm + spacing.xxs, fontSize: 10, fontWeight: typography.weight.medium, textAlign: 'center' },
  activitySummaryValue: { marginTop: spacing.xs, fontSize: typography.size.lg, fontWeight: typography.weight.medium },
  activitySummaryFooter: { marginTop: spacing.xs + spacing.xxs, fontSize: 9, fontWeight: typography.weight.medium, textAlign: 'center' },
  activityGroup: { gap: spacing.sm },
  activityGroupTitle: { paddingHorizontal: spacing.xs - 1, fontSize: typography.size.sm, fontWeight: typography.weight.extraBold },
  activityList: { borderWidth: border.thin, borderRadius: radius.lg, paddingHorizontal: spacing.md, overflow: 'hidden' },
  activityRow: { minHeight: 75, flexDirection: 'row', alignItems: 'center', gap: spacing.sm + spacing.xxs },
  activityRowNew: { position: 'relative', marginHorizontal: -12, paddingHorizontal: 12 },
  activityNewAccent: { position: 'absolute', left: 0, top: 10, bottom: 10, width: 3, borderTopRightRadius: 3, borderBottomRightRadius: 3 },
  activityLeadingIcon: { width: 48, height: 48, borderRadius: radius.md + 2, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  activityRowContent: { flex: 1, minWidth: 0, gap: 2 },
  activityRowTitleLine: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  activityTitle: { minWidth: 0, flexShrink: 1, fontSize: 13, fontWeight: typography.weight.extraBold },
  activityNewPill: { minHeight: 17, borderRadius: 9, paddingHorizontal: 6, alignItems: 'center', justifyContent: 'center' },
  activityNewPillText: { color: palette.white, fontSize: 8, lineHeight: 10, fontWeight: typography.weight.black },
  activityPartner: { fontSize: 11, fontWeight: typography.weight.medium },
  activityStatus: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  activityStatusText: { fontSize: 10, fontWeight: typography.weight.medium },
  activityTime: { minWidth: 62, alignItems: 'flex-end', gap: 3 },
  activityDate: { fontSize: 10, fontWeight: typography.weight.medium },
  activityClock: { fontSize: 10, fontWeight: typography.weight.medium },
  activityIelts: { paddingHorizontal: spacing.xs + 1, paddingVertical: spacing.sm - 1, borderRadius: radius.xs + 1, backgroundColor: palette.slate[700] },
  activityIeltsText: { color: palette.white, fontSize: 8, fontWeight: typography.weight.black },
  activityKycText: { position: 'absolute', color: palette.white, fontSize: 7, fontWeight: typography.weight.black },
  activityShieldOverlay: { position: 'absolute' },
  activityFilterOverlay: { flex: 1, justifyContent: 'flex-end' },
  activityFilterBackdrop: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(11, 15, 26, 0.42)' },
  activityFilterSheet: {
    borderTopWidth: border.thin,
    borderTopLeftRadius: radius.xxl,
    borderTopRightRadius: radius.xxl,
    paddingHorizontal: spacing.lg + spacing.xxs,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl + spacing.xs,
    gap: spacing.lg + spacing.xxs,
  },
  activityFilterHeader: { flexDirection: 'row', alignItems: 'center' },
  activityFilterTitle: { flex: 1, fontSize: 19, fontWeight: typography.weight.extraBold },
  activityFilterClose: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  activityFilterSection: { gap: 9 },
  activityFilterSectionTitle: { fontSize: 13, fontWeight: typography.weight.extraBold },
  activityFilterOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  activityFilterOption: { minHeight: 42, borderWidth: border.thin, borderRadius: radius.round, paddingHorizontal: 15, alignItems: 'center', justifyContent: 'center' },
  activityFilterOptionText: { fontSize: typography.size.xs, fontWeight: typography.weight.semibold },
  activityFilterActions: { flexDirection: 'row', gap: 10, marginTop: 2 },
  activityFilterReset: { flex: 1, minHeight: componentSize.buttonHeight, borderWidth: border.thin, borderRadius: radius.md + 2, alignItems: 'center', justifyContent: 'center' },
  activityFilterResetText: { fontSize: typography.size.sm, fontWeight: typography.weight.bold },
  activityFilterApply: { flex: 1, minHeight: componentSize.buttonHeight, borderRadius: radius.md + 2, alignItems: 'center', justifyContent: 'center' },
  activityFilterApplyText: { color: palette.white, fontSize: typography.size.sm, fontWeight: typography.weight.extraBold },
  settingsScreenContent: { paddingTop: spacing.xs + 1, paddingBottom: spacing.xl + spacing.xs, gap: spacing.md + spacing.xxs },
  settingsBrandHeader: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  settingsHeaderButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  settingsBrandLogo: { flex: 1, marginLeft: 6 },
  settingsIntro: { gap: 3, marginTop: 1, marginBottom: 2 },
  settingsScreenTitle: { fontSize: typography.size.xl, lineHeight: typography.lineHeight.xl - 2, fontWeight: typography.weight.black, letterSpacing: -0.6 },
  settingsScreenSubtitle: { fontSize: typography.size.sm, lineHeight: typography.lineHeight.sm },
  backupCard: { minHeight: 108, borderWidth: border.thin, borderRadius: radius.lg + 2, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.md + 1 },
  backupIcon: { width: 62, height: 62, borderRadius: radius.lg - 1, alignItems: 'center', justifyContent: 'center' },
  backupTitle: { fontSize: 17, fontWeight: typography.weight.extraBold },
  backupDescription: { fontSize: 11, lineHeight: 16, marginTop: 3 },
  backupStatus: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: spacing.xs, marginTop: spacing.xs + 1, borderRadius: radius.round, backgroundColor: palette.green[100], paddingHorizontal: spacing.sm - 1, paddingVertical: spacing.xs - 1 },
  backupStatusText: { fontSize: 9.5, fontWeight: typography.weight.semibold },
  settingsSectionTitle: { fontSize: typography.size.sm, lineHeight: typography.lineHeight.sm, fontWeight: typography.weight.extraBold, marginTop: spacing.xxs, marginHorizontal: 1 },
  settingsList: { paddingVertical: 0, elevation: 1, shadowOpacity: 0.035, shadowRadius: 8 },
  settingsRow: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  settingsIcon: { width: 38, height: 38, borderRadius: radius.md - 1, alignItems: 'center', justifyContent: 'center' },
  settingsTitle: { fontSize: 13.5, fontWeight: typography.weight.extraBold },
  settingsDescription: { fontSize: 10.5, lineHeight: 15, marginTop: 3 },
  themeCard: { flexDirection: 'row', gap: spacing.sm, padding: spacing.sm + spacing.xxs },
  themeOption: { flex: 1, minHeight: 90, borderWidth: border.thin, borderRadius: radius.md + 2, alignItems: 'center', justifyContent: 'center', gap: spacing.xs + spacing.xxs },
  themeLabel: { fontSize: 10, fontWeight: typography.weight.extraBold, textAlign: 'center' },
  languageRow: { minHeight: 74, flexDirection: 'row', alignItems: 'center' },
  sampleSettingsDescription: { fontSize: 14, lineHeight: 21, marginHorizontal: 2 },
  helpHero: { alignItems: 'center', paddingHorizontal: 26 },
  helpIcon: { width: 80, height: 80, borderRadius: 40, alignItems: 'center', justifyContent: 'center' },
  helpTitle: { marginTop: 15, fontSize: 21, fontWeight: typography.weight.black },
  helpText: { marginTop: 7, fontSize: 14, lineHeight: 21, textAlign: 'center' },
  helpRow: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 10 },
  aboutRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  aboutLabel: { fontSize: 13, fontWeight: typography.weight.semibold },
  aboutValue: { fontSize: 13, fontWeight: typography.weight.extraBold },
});
