export const assetManifest = {
  app: {
    identraLogo: require('../../assets/images/optimized/identra-logo-180h.png'),
    studentAvatar: require('../../assets/images/optimized/student-avatar-360.jpg'),
  },
  badges: {
    verified: require('../../assets/images/verified-badge-icon.png'),
  },
  chat: {
    avatars: {
      catMask: require('../../assets/images/chat-list-demo-icon/macos-tahoe.jpg'),
      catFlower: require('../../assets/images/chat-list-demo-icon/photo_2026-06-21_11-00-02.jpg'),
      avatarA: require('../../assets/images/chat-list-demo-icon/photo_2026-06-21_11-00-02 (2).jpg'),
      avatarB: require('../../assets/images/chat-list-demo-icon/photo_2026-06-21_11-00-02 (3).jpg'),
      avatarC: require('../../assets/images/chat-list-demo-icon/photo_2026-06-21_11-00-02 (4).jpg'),
      avatarD: require('../../assets/images/chat-list-demo-icon/photo_2026-06-21_11-00-02 (5).jpg'),
      avatarE: require('../../assets/images/chat-list-demo-icon/photo_2026-06-21_11-00-03.jpg'),
      avatarF: require('../../assets/images/chat-list-demo-icon/photo_2026-06-21_11-00-03 (2).jpg'),
      avatarG: require('../../assets/images/chat-list-demo-icon/photo_2026-06-21_11-00-03 (3).jpg'),
      avatarH: require('../../assets/images/chat-list-demo-icon/photo_2026-06-21_11-00-03 (4).jpg'),
    },
    reels: {
      sunset: require('../../assets/images/reels-demo/optimized/sunset-reel-720x1280.jpg'),
      cafe: require('../../assets/images/reels-demo/726539144_18593915638019516_4984287053884373130_n.jpg'),
    },
  },
  miniApps: {
    bee: require('../../assets/images/mini-app-logo/bee-icon.png'),
    publicService: require('../../assets/images/mini-app-logo/quoc-huy-vn-icon.png'),
  },
  miniAppDemo: {
    banners: {
      hero: require('../../assets/images/mini-app-demo/optimized/miniapp-big-banner-1080w.jpg'),
      publicService: require('../../assets/images/mini-app-demo/optimized/dich-vu-cong-second-banner-1080w.jpg'),
      transport: require('../../assets/images/mini-app-demo/optimized/di-chuyen-second-banner-1080w.jpg'),
    },
    icons: {
      socialInsurance: require('../../assets/images/mini-app-demo/optimized/bao-hiem-xa-hoi-icon.png'),
      bee: require('../../assets/images/mini-app-demo/optimized/bee-datxe-icon.png'),
      mirae: require('../../assets/images/mini-app-demo/optimized/chung-khoan-mirae-icon.png'),
      temporaryResidence: require('../../assets/images/mini-app-demo/optimized/dang-ky-tam-tru-icon.png'),
      entertainment: require('../../assets/images/mini-app-demo/optimized/giai-tri-icon.png'),
      publicEducation: require('../../assets/images/mini-app-demo/optimized/giao-duc-cong-icon.png'),
      education: require('../../assets/images/mini-app-demo/optimized/giao-duc-icon.png'),
      civilStatus: require('../../assets/images/mini-app-demo/optimized/ho-tich-icon.png'),
      shopping: require('../../assets/images/mini-app-demo/optimized/mua-sam-icon.png'),
      trafficFine: require('../../assets/images/mini-app-demo/optimized/nop-phat-giao-thong-icon.png'),
      publicService: require('../../assets/images/mini-app-demo/optimized/quoc-huy-icon.png'),
      finance: require('../../assets/images/mini-app-demo/optimized/tai-chinh-icon.png'),
      payment: require('../../assets/images/mini-app-demo/optimized/thanh-toan-icon.png'),
      personalTax: require('../../assets/images/mini-app-demo/optimized/thue-ca-nhan-icon.png'),
      lookupTrafficFine: require('../../assets/images/mini-app-demo/optimized/tra-cuu-phat-nguoi-icon.png'),
      viettel: require('../../assets/images/mini-app-demo/optimized/viettel-icon.png'),
      publicHealth: require('../../assets/images/mini-app-demo/optimized/y-te-cong-icon.png'),
    },
  },
  newsFeed: {
    identraFeed: require('../../assets/images/news-feed-demo/optimized/identra-feed-demo-960w.jpg'),
    dalat: require('../../assets/images/news-feed-demo/optimized/dalat-live-preview-960x1044.jpg'),
    linh: require('../../assets/images/news-feed-demo/optimized/linh-feed-960w.jpg'),
  },
  payment: {
    demoBanners: [
      require('../../assets/images/payment-demo/optimized/demo-banner-1-1080w.jpg'),
      require('../../assets/images/payment-demo/optimized/demo-banner-2-1080w.jpg'),
      require('../../assets/images/payment-demo/optimized/demo-banner-3-1080w.jpg'),
      require('../../assets/images/payment-demo/optimized/demo-banner-4-1080w.jpg'),
    ],
    specialOffers: [
      require('../../assets/images/payment-demo/optimized/special-offer-1-540w.jpg'),
      require('../../assets/images/payment-demo/optimized/special-offer-2-540w.jpg'),
      require('../../assets/images/payment-demo/optimized/special-offer-3-540w.jpg'),
      require('../../assets/images/payment-demo/optimized/special-offer-4-540w.jpg'),
      require('../../assets/images/payment-demo/optimized/special-offer-5-540w.jpg'),
      require('../../assets/images/payment-demo/optimized/special-offer-6-540w.jpg'),
      require('../../assets/images/payment-demo/optimized/special-offer-7-540w.jpg'),
      require('../../assets/images/payment-demo/optimized/special-offer-8-540w.jpg'),
    ],
  },
} as const;
